- link:
    ~/.config/fish/config.fish: fish/config/config.fish
    ~/.config/fish/completions/fisher.fish: fish/config/completions/fisher.fish
    ~/.config/fish/completions/alacritty.fish: fish/config/completions/alacritty.fish
    ~/.config/fish/fishfile: fish/config/fishfile
    ~/.config/fish/functions/fisher.fish: fish/config/functions/fisher.fish
- shell:
    - command: fisher; true
      description: Install fisher packages
