- link:
    /usr/share/fonts/opentype/DankMono-Regular-nfc.otf: "private/fonts/DankMono-Regular-nfc.otf"
    /usr/share/fonts/opentype/DankMono-Italic-nfc.otf: "private/fonts/DankMono-Italic-nfc.otf"
